# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - uv run pytest

  tag:
    vars:
      VERSION:
        sh: uv version --short
    cmds:
      - git tag -s -a {{ .VERSION }} -m "Release {{ .VERSION }}"
